site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'

plugins:
  - techdocs-core

nav:
  - Readme:
      - test?: '../README.md'
  - Overview:
      - What is Backstage?: 'test.md'
      
